### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by Ibirtem** [lemon-slice-studio/After-the-Drizzle#1]
I don’t know whose mod can cause crashes, but this only happens when this mod is installed :(
They are all different.

Crash going on when i start any world. In crash folder appears two diffirent files:
Server: https://gist.github.com/Ibirtem/54e25e7186e42dcdc2ca7e0c62a6d605
Client: https://gist.github.com/Ibirtem/a0b3b680a5e85e3c8f8f73f155698b02

**Comment by RoShioLeo** [comment]
Thank you. I'm trying to fix it, but I couldn't reproduce it. I'm so confused now.

**Comment by Ibirtem** [comment]
i found what it can be (if it help you)
Biomes O' Plenty
 There clear crash report: https://gist.github.com/Ibirtem/a3882eff1fea8c09236902ac9cdc2d31

**Comment by RoShioLeo** [comment]
That's helpful, thanks very much.

**Comment by RoShioLeo** [comment]
OK, I know why it crashed. I'll fix it soon.

**Comment by RoShioLeo** [comment]
The bug has been fixed. Thank you!
