### ISSUE TITLE
Tooltip Server Crash 

### ISSUE THREAD

**Issue by WenXin20** [lemon-slice-studio/After-the-Drizzle#5]
`Minecraft v1.15.2`
`Forge v31.2.45`
`After the Drizzle v1.0.8-beta`

My server crashed during load. It looks to be related to the tooltips.
[Crash Report](https://gist.github.com/WenXin20/ba0a83c99a263b58d9c3594b1b6fa754)

**Comment by RoShioLeo** [comment]
1.0.9-Beta fixed.
