### ISSUE TITLE
Missing Tags

### ISSUE THREAD

**Issue by WenXin20** [lemon-slice-studio/After-the-Drizzle#6]
`Minecraft v1.15.2`
`Forge v31.2.45`
`After the Drizzle v1.0.8-beta`

The doors are also missing the block and item tag `minecraft:doors` & `minecraft:wooden_doors`, which villagers to open doors.
The flowers are missing the tag `minecraft:small_flowers`, which would allow bees to pollinate them.

**Comment by RoShioLeo** [comment]
OK. I forgot to add flowers' blocks to the tag, but items did.
New version will be soon.

**Comment by WenXin20** [comment]
Thanks!
